/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cover: typeof import('./src/components/Cover/index.vue')['default']
    Dom2Image: typeof import('./src/components/Dom2Image/index.vue')['default']
    GieInput: typeof import('@giegie/components')['GieInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
