/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cover: typeof import('./../components/Cover/index.vue')['default']
    Dom2Image: typeof import('./../components/Dom2Image/index.vue')['default']
    ImageCompress: typeof import('./../components/ImageCompress/index.vue')['default']
    PDFJS: typeof import('./../components/PDFJS/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
